### ISSUE TITLE
Manual Selection

### ISSUE THREAD

**Issue by aribrown100** [lazzzyapp/lazzzy-extension#37]
# Lazzzy Exention Bug Report

When doing manual selection grey line cutting off paragraph on left in our notepad

## Process

Steps to replicate the behavior:

1. Go to manual selection
2. Click on any paragraph
3. Highlight pops up in our lazzzy notepad, but grey line is present

## Expectation

Grey line should not be there

## Screenshot

<img width="1440" alt="Screen Shot 2021-10-22 at 12 17 47 PM" src="https://user-images.githubusercontent.com/55774460/138489418-a220147d-b494-4ee5-81da-30a6fe8dd14a.png">

## Details

Details about your particular case so that we can mirror them

- Name of Notebook Provider Github
- Name of Browser Chrome
- Version Number of Browser // 94.0.4606.71

## Additional Context

Hope this is helpful!

**Comment by xcesiv** [comment]
This has been resolved in [v0.0.1-alpha](https://github.com/lazzzyapp/lazzzy-extension/releases/tag/v0.0.1-alpha)
